[deps]
RxInfer = "86711068-29c9-4ff7-b620-ae75d7495b3d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"