name = "RxInferLLM"
uuid = "6f1d9b8a-3c4b-4f09-9d2a-123456789abc"
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
OpenAI = "e9f21f70-7185-4079-aca2-91159181367c"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ReactiveMP = "a194aa59-28ba-4574-a09c-4a745416d6e3"
RxInfer = "86711068-29c9-4ff7-b620-ae75d7495b3d"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
