name = "VisualizationMethods"
uuid = "2f6f5b8a-42b9-4c4c-9d6d-7b3b1b6f9d3a"
authors = ["RxInferExamples Maintainers"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RxInfer = "86711068-29c9-4ff7-b620-ae75d7495b3d"
GraphViz = "f526b714-d49f-11e8-06ff-31ed36ee7ee0"

[compat]
julia = ">= 1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
