name = "CoinToss"
uuid = "e69f238d-138a-4550-bbc7-c3a8dd46badf"
version = "0.1.0"

[deps]
RxInfer = "86711068-29c9-4ff7-b620-ae75d7495b3d"
ReactiveMP = "a194aa59-28ba-4574-a09c-4a745416d6e3"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"

